### ISSUE TITLE
No files generated for adaptive-card.json

### ISSUE THREAD

**Issue by RappC** [jsonschema2dataclass/js2d-gradle#351]
I'm trying to create Java classes for the schema https://adaptivecards.io/schemas/adaptive-card.json which I have stored in `src/main/resources/json/adaptive-card.json`

Gradle task runs successfully and output directory is created. But the output directory does not contain any files. 
When running gradle with `--debug` option I don't see any suspicious output. 

* `build.gradle`
  ```
  buildscript {
    repositories {
      mavenCentral()
    }
  }
  
  plugins {
    id "java"
    id "org.jsonschema2dataclass" version "4.2.0"
  }
  
  sourceCompatibility = JavaVersion.VERSION_11
  
  jsonSchema2Pojo {
    targetPackage = 'io.adaptivecards.schemas' // specify package for your needs
  
    source.setFrom files("${project.rootDir}/src/main/resources/json")
  
    // ... — add other supported options as you need
  }
  ...
  ```
* Gradle Version: 7.4.2

**Comment by eirnym** [comment]
Thank you for an issue. I also have same issues with other similar files as well, so I do following actions every time main json file is changed (so I don't need to do it every time). Following actions are safe and won't be affect validation process.

Please comment to the issue if you have any questions

There's a few issues for an underlying library I can't fix for you here. But I can give you a few recommendations of one-time actions (per edit) to mitigate some of the problems of the issue

1) Rename all entities defined in the json such `Action.OpenUrl` to `Action_OpenUrl`. It's because the internal way, how underlying library addresses entities. Referable entity names are not enforced by JSON syntax, so it's possible to name all entities as you please without affecting the validation.
For json I'd recommend following regexes (in IntelliJ Idea syntax, please adjust to your tools): 
     * `"([^"]*/[A-Za-z]*)\.([A-Za-z]*)"` -> `"$1_$2"` - this replaces references
     * `"([A-Za-z]*)\.([A-Za-z]*)"` -> `"$1_$2"`  - this replaces names
2) Create files for each node as root node of main file is empty. For json I used `jq` tool (for `yaml` I use simple sed)
Generated json files needs look like `{"$ref": "main_file.json/#/definitions/entity_name"}`, for yaml `$ref: main_file.json/#/definitions/entity_name`
Command I used for this json file is below in the same folder as the `adaptive-card.json`.
```sh
jq '.definitions | keys[]' $filename_to_split \
  |  sed 's,",,g'  \
  | while read jkey; do  \
     echo "{\"\$ref\": \"./$filename_to_split/#/definitions/$jkey\"}" > "$jkey.json"; \
   done 
```
3) `allOf` isn't processed by underlying generator, and in this case you need to manually add `extends` elements to make sure, that inheritance is working properly. This is important for such entities as `Extendable.ToggleableItem`. This is an extension, so validation won't be altered in any way. However,  there's no clear way to generate a data class from such definitions in general case as `allOf` refers to multi-inheritance, which is not available in Java
4) `anyOf` and other conditionals is not processed by underlying library. In this particular case it's easy for `implementationsOf` objects, as all elements have a common root item that can be used in code without changing the schema. In this particular case I'd add `extends` keyword as well. However,  there's no clear way to generate a data class from such definitions in general case.

**Comment by eirnym** [comment]
I close the issue, feel free to reopen or discuss it further it in any time
