### ISSUE TITLE
Plugin is incompatible with Gradle 8 if used together with JavaPluginExtension.withSourcesJar()

### ISSUE THREAD

**Issue by erdi** [jsonschema2dataclass/js2d-gradle#676]
In such configuration executing the `sourcesJar` task added by `JavaPluginExtension.withSourcesJar()` results in
```
A problem was found with the configuration of task 'sourcesJar' (type 'Jar').
  - Gradle detected a problem with the following location: 'build/generated/sources/js2d/main'.
    
    Reason: Task 'sourcesJar' uses this output of task 'generateJsonSchema2DataClassConfigMain' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
```

I believe this is down to using a `Path` at https://github.com/jsonschema2dataclass/js2d-gradle/blob/main/plugin-gradle/compat/java/src/main/kotlin/org/jsonschema2dataclass/internal/compat/java/JavaPluginRegistration.kt#L48 rather than using a `org.gradle.api.file.DirectoryProperty` tied to a `Js2dGeneratorTaskBase` instance.

**Comment by eirnym** [comment]
Thank you, it's a nice find!

**Comment by eirnym** [comment]
@erdi Could you please supply a minimal project to reproduce the issue?

**Comment by eirnym** [comment]
I've read about the `JavaPluginExtension.withSourcesJar()` and an implementation in Gradle 7.6. It's a nice touch by Gradle team, I didn't know about.

I don't see how using `Path` instead of `DirectoryProperty` would solve the issue. Maybe, Gradle marks "this folder is an output from an another task, so we set an implicit dependency. Since all implicit dependencies are going to be deprecated further along the road, I don't see this replacement will solve the issue.

I see here few obstacles with attaching to that task:
1) Only main source set is considered by the task. To mitigate that I might consider to create an additional source set and set a dependencies to it from the `main`.
2) Task is created by this method and name is generated by source set itself. Theoretically I can take the name from `main` source set and try to "watch" task creation if needed. Nevertheless, there's no guarantee, that a developer would create a task with the same name in other way and provide another meaning to that.

Thus, I'm asking for a PRs: one with a java demo for that and one for solving the issue. For current version I suggest to configure dependencies manually in Gradle script like it's done in [model-publish](https://github.com/jsonschema2dataclass/js2d-gradle/blob/main/demo/java/model-publish/build.gradle.kts) demo

**Comment by erdi** [comment]
Hi @eirnym,

I've just pushed a commit with a test that reproduces the issue at https://github.com/erdi/js2d-gradle/commit/df9d9baa84f2fe36109f6b883c34383a74302dee. I will now see if I can figure out a fix and if I do then I will open a PR.

**Comment by erdi** [comment]
Can I please have a workflow approval on my draft PR at https://github.com/jsonschema2dataclass/js2d-gradle/pull/689, @eirnym?

**Comment by erdi** [comment]
It turns out that the fix was very easy to implement because `ProcessorRegistrationCallback.registerDependencies()` takes a task provider as the first argument.

**Comment by eirnym** [comment]
Thank you, I'll have a look
