### ISSUE TITLE
constructors.allPropeties seems to default to true

### ISSUE THREAD

**Issue by StefanLobbenmeierObjego** [jsonschema2dataclass/js2d-gradle#825]
I just migrated from 4.3.1 to 6.0.0

Afterwards I compared the generated sources, and discovered that now there were new constructors generated. I checked the documentation and it suggested that the default for this was false:
https://github.com/jsonschema2dataclass/js2d-gradle/blob/main/docs/usage/parameters_6.adoc#constructor-parameters

I changed this explicitly to false now:
```build.gradle.kts
            constructors {
                allProperties = false
            }
```

 which seems to have done the trick. So please either change the default back or reflect this in the documentation.

**Comment by StefanLobbenmeierObjego** [comment]
FYI this is the structure before:
```build.gradle.kts
jsonSchema2Pojo {
    targetPackage.set("mypackage")
    source.setFrom("${project.rootDir}/src/main/resources/schema")
    generateBuilders.set(true)
    dateTimeType.set("java.time.ZonedDateTime")
    dateType.set("java.time.LocalDate")
}
```

and after:
```build.gradle.kts
jsonSchema2Pojo {
    executions {
        create("main") {
            klass {
                targetPackage.set("mypackage")
            }
            io {
                source.setFrom("${project.rootDir}/src/main/resources/schema")
            }
            methods {
                builders.set(true)
            }
            dateTime {
                dateTimeType.set("java.time.ZonedDateTime")
                dateType.set("java.time.LocalDate")
            }
            constructors {
                allProperties.set(false)
            }
        }
    }
}
```

**Comment by StefanLobbenmeierObjego** [comment]
This seems to come from jsonschema2pojo:
org/jsonschema2pojo/DefaultGenerationConfig.java:319

![image](https://github.com/jsonschema2dataclass/js2d-gradle/assets/122794560/fdd62023-c7f8-431f-866f-0a13f8d96dbd)

**Comment by eirnym** [comment]
Hi @StefanLobbenmeierObjego, thank you for an issue. I'll look into it.

**Comment by eirnym** [comment]
Thank you for your time, I've looked into it. 

Plugin doesn't provide any explicit defaults beside few options removed from the public interface and well documented in the [migration document](https://github.com/jsonschema2dataclass/js2d-gradle/blob/main/docs/migration/migration_6.adoc#options-removed). If some defaults has been changed in underlying processor, a user would experience sudden behaviour change.

Behavior of many other similar plugins (for example, Spotless) is similar to what has been implemented in the this plugin. Nevertheless, I'll accept any help (ideas and/or PRs), If there would be any ideas how to mitigate such sudden changes for a user.

Please note, that a plugin user can control processor version in several ways ways
*  by using the same plugin version
* by explicitly specifying the version of the processor, as it shown in [demos](https://github.com/jsonschema2dataclass/js2d-gradle/tree/main/demo/java/classpath).

Please mind, off-release upgrades might not work as the processor might be incompatible with the current plugin version due to interface changes as it was before with `jsonschema2pojo` processor.

**Comment by eirnym** [comment]
I'm closing this issue as resolved. You're welcome to ask for more information.
